### ISSUE TITLE
Rev 1.0 status tracking

### ISSUE THREAD

**Issue by daveshah1** [daveshah1/TrellisBoard#5]
Features tested so far:
 - [x] FT2232H JTAG and UART
 - [ ] FT2232H parallel mode
 - [x] USB powered
 - [ ] 12V power circuitry and connector
 - [x] LEDs
 - [x] Buttons and DIP switches
 - [x] DDR3 (tested up to 400Mbps at present)
 - [x] Ethernet PHY
 - [x] TFP410 HDMI (tested up to 1080p30 at present)
 - [ ] USB ULPI PHY
 - [ ] Clock generator
 - [ ] PCIe
 - [ ] M.2
 - [ ] FFCs
 - [ ] PMOD
 - [ ] micro SD

**Comment by ki5libs** [comment]
Hi @daveshah1,

does FFC actual placement let you to use them? I see in the [datasheet](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F1734839%7FC%7Fpdf%7FEnglish%7FENG_CD_1734839_C_C_1734839.pdf%7F4-1734839-0) that actuator opens down so connector should be very close to the board edge. How is it really?

**Comment by daveshah1** [comment]
I haven't actually got a suitable cable to test with. On the board I have, it seems to move in and out alright at least. But maybe they should be moved to the edge in the next revision.

**Comment by ki5libs** [comment]
Hi @daveshah1,

have you already checked clock from U26 oscillator? I'm just a little bit confused with not connected E/D pin...

**Comment by daveshah1** [comment]
Hi @ki5libs, see #2 - it should be going into a PCLK pair on the left or right side, ideally near the DDR3. As it stands I've been using the 12MHz clock instead.

**Comment by ki5libs** [comment]
@daveshah1, yes, I saw that. Maybe I wasn't clear enough, I just want to ask did you check U26 output in general. Is clock OK on both OUT pins without external pull-up resistor. I didn't noticed that datasheet has information about internal pull-up. Sorry, nevermind.
